import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    "detect_hardware",
    Path(__file__).resolve().parent.parent / "scripts" / "detect_hardware.py",
)
detect_hardware = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(detect_hardware)


def test_parse_gpu_query_ranks_by_total_vram_desc():
    csv = (
        "GPU-1070uuid, NVIDIA GeForce GTX 1070, 8192\n"
        "GPU-5090uuid, NVIDIA GeForce RTX 5090, 32607\n"
    )
    gpus = detect_hardware.parse_gpu_query(csv)
    assert [g["uuid"] for g in gpus] == ["GPU-5090uuid", "GPU-1070uuid"]
    assert gpus[0]["name"] == "NVIDIA GeForce RTX 5090"
    assert gpus[0]["memory_total_mib"] == 32607


def test_parse_gpu_query_empty_returns_empty_list():
    assert detect_hardware.parse_gpu_query("") == []


def test_build_gpu_assignments_pins_services_to_biggest():
    gpus = [
        {"uuid": "GPU-5090uuid", "name": "RTX 5090", "memory_total_mib": 32607},
        {"uuid": "GPU-1070uuid", "name": "GTX 1070", "memory_total_mib": 8192},
    ]
    assigns = detect_hardware.build_gpu_assignments(gpus)
    assert assigns["llamacpp"] == "GPU-5090uuid"
    assert assigns["comfyui"] == "GPU-5090uuid"
    assert assigns["llamacpp-embed"] == "GPU-5090uuid"


def test_build_gpu_assignments_no_gpus_is_empty():
    assert detect_hardware.build_gpu_assignments([]) == {}


def test_format_gpu_assignments_emits_device_ids_yaml():
    yaml = detect_hardware.format_gpu_assignments({"llamacpp": "GPU-5090uuid"})
    assert "# Auto-generated by scripts/detect_hardware.py" in yaml
    assert "services:" in yaml
    assert "  llamacpp:" in yaml
    assert 'device_ids: ["GPU-5090uuid"]' in yaml
    assert "capabilities: ['gpu']" in yaml
    assert "count:" not in yaml


def test_nvidia_compute_override_has_no_gpu_compute_reservations():
    overrides = detect_hardware.build_overrides(
        llamacpp_mem="100G", comfyui_mem="42G",
        embed_mem="6G", common_sidecars={},
    )
    text = detect_hardware.format_override(overrides["nvidia"])
    assert "device_ids" not in text
    # The only remaining `driver: nvidia` line is the dashboard's utility-only
    # reservation (NVML stats, no GPU compute). Compute services must have none.
    assert text.count("driver: nvidia") <= 1
    assert "mem_limit: 100G" in text  # mem limits still present


def test_update_env_appends_gpu_assignments_after_compute(tmp_path):
    env = tmp_path / ".env"
    env.write_text("FOO=bar\n", encoding="utf-8")
    detect_hardware.update_env(env, mode="nvidia", sep=";")
    content = env.read_text(encoding="utf-8")
    assert "COMPOSE_FILE=docker-compose.yml;overrides/compute.yml;overrides/gpu-assignments.yml" in content


def test_update_env_no_gpu_assignments_for_cpu(tmp_path):
    env = tmp_path / ".env"
    env.write_text("FOO=bar\n", encoding="utf-8")
    detect_hardware.update_env(env, mode="cpu", sep=":")
    content = env.read_text(encoding="utf-8")
    assert "gpu-assignments.yml" not in content
    assert "COMPOSE_FILE=docker-compose.yml:overrides/compute.yml" in content
