import importlib.util
import sys
from pathlib import Path
from unittest.mock import MagicMock

# Mock docker before loading ops-controller
sys.modules.setdefault("docker", MagicMock())

_spec = importlib.util.spec_from_file_location(
    "ops_main",
    Path(__file__).resolve().parent.parent / "ops-controller" / "main.py",
)
ops_main = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ops_main)

SAMPLE = """# Auto-generated by scripts/detect_hardware.py
# Machine-local: gitignored. Edit via the dashboard GPU tab.
services:
  llamacpp:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-5090"]
              capabilities: ['gpu']
  comfyui:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-1070"]
              capabilities: ['gpu']
"""


def test_parse_gpu_assignments_yaml():
    assert ops_main.parse_gpu_assignments_yaml(SAMPLE) == {
        "llamacpp": "GPU-5090", "comfyui": "GPU-1070",
    }


def test_parse_gpu_assignments_yaml_empty():
    assert ops_main.parse_gpu_assignments_yaml("") == {}


def test_render_gpu_assignments_roundtrip():
    m = {"llamacpp": "GPU-5090", "comfyui": "GPU-1070"}
    assert ops_main.parse_gpu_assignments_yaml(ops_main.render_gpu_assignments(m)) == m


def test_apply_gpu_assignment_updates_one_service(tmp_path, monkeypatch):
    path = tmp_path / "gpu-assignments.yml"
    path.write_text(ops_main.render_gpu_assignments(
        {"llamacpp": "GPU-5090", "comfyui": "GPU-5090"}), encoding="utf-8")
    monkeypatch.setattr(ops_main, "GPU_ASSIGNMENTS_PATH", path)
    ops_main.apply_gpu_assignment("comfyui", "GPU-1070")
    assert ops_main.parse_gpu_assignments_yaml(path.read_text()) == {
        "llamacpp": "GPU-5090", "comfyui": "GPU-1070",
    }


def test_apply_gpu_assignment_adds_missing_service(tmp_path, monkeypatch):
    path = tmp_path / "gpu-assignments.yml"
    path.write_text(ops_main.render_gpu_assignments({"llamacpp": "GPU-5090"}), encoding="utf-8")
    monkeypatch.setattr(ops_main, "GPU_ASSIGNMENTS_PATH", path)
    ops_main.apply_gpu_assignment("llamacpp-embed", "GPU-1070")
    assert ops_main.parse_gpu_assignments_yaml(path.read_text()) == {
        "llamacpp": "GPU-5090", "llamacpp-embed": "GPU-1070",
    }
