import importlib.util
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

# Mock docker before loading ops-controller
sys.modules.setdefault("docker", MagicMock())

_spec = importlib.util.spec_from_file_location(
    "ops_main",
    Path(__file__).resolve().parent.parent / "ops-controller" / "main.py",
)
ops_main = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ops_main)

SAMPLE = """# Auto-generated by scripts/detect_hardware.py
# Machine-local: gitignored. Edit via the dashboard GPU tab.
services:
  llamacpp:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-5090"]
              capabilities: ['gpu']
  comfyui:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-1070"]
              capabilities: ['gpu']
"""


def test_parse_gpu_assignments_yaml():
    assert ops_main.parse_gpu_assignments_yaml(SAMPLE) == {
        "llamacpp": "GPU-5090", "comfyui": "GPU-1070",
    }


def test_parse_gpu_assignments_yaml_empty():
    assert ops_main.parse_gpu_assignments_yaml("") == {}


def test_render_gpu_assignments_roundtrip():
    m = {"llamacpp": "GPU-5090", "comfyui": "GPU-1070"}
    assert ops_main.parse_gpu_assignments_yaml(ops_main.render_gpu_assignments(m)) == m


def test_render_gpu_assignments_emits_cuda_visible_devices():
    # WSL2/Docker Desktop ignores device_ids isolation; CUDA_VISIBLE_DEVICES
    # is what actually pins each service to its assigned GPU.
    text = ops_main.render_gpu_assignments({"comfyui": "GPU-1070"})
    assert "CUDA_VISIBLE_DEVICES=GPU-1070" in text
    assert "NVIDIA_VISIBLE_DEVICES=GPU-1070" in text


def test_apply_gpu_assignment_updates_one_service(tmp_path, monkeypatch):
    path = tmp_path / "gpu-assignments.yml"
    path.write_text(ops_main.render_gpu_assignments(
        {"llamacpp": "GPU-5090", "comfyui": "GPU-5090"}), encoding="utf-8")
    monkeypatch.setattr(ops_main, "GPU_ASSIGNMENTS_PATH", path)
    ops_main.apply_gpu_assignment("comfyui", "GPU-1070")
    assert ops_main.parse_gpu_assignments_yaml(path.read_text()) == {
        "llamacpp": "GPU-5090", "comfyui": "GPU-1070",
    }


def test_apply_gpu_assignment_adds_missing_service(tmp_path, monkeypatch):
    path = tmp_path / "gpu-assignments.yml"
    path.write_text(ops_main.render_gpu_assignments({"llamacpp": "GPU-5090"}), encoding="utf-8")
    monkeypatch.setattr(ops_main, "GPU_ASSIGNMENTS_PATH", path)
    ops_main.apply_gpu_assignment("llamacpp-embed", "GPU-1070")
    assert ops_main.parse_gpu_assignments_yaml(path.read_text()) == {
        "llamacpp": "GPU-5090", "llamacpp-embed": "GPU-1070",
    }


# --- HTTP guard tests for POST /gpu/assign ---

@pytest.fixture
def http_client(monkeypatch):
    """Return a TestClient for ops_main.app with a known token set."""
    from fastapi.testclient import TestClient
    monkeypatch.setattr(ops_main, "OPS_CONTROLLER_TOKEN", "testtok")
    return TestClient(ops_main.app, raise_server_exceptions=False)


_VALID_UUID = "GPU-12345678-1234-1234-1234-123456789abc"
_AUTH = {"Authorization": "Bearer testtok"}


def test_gpu_assign_rejects_non_allowlisted_service(http_client):
    """Service not in GPU_ASSIGNABLE_SERVICES → 400."""
    resp = http_client.post(
        "/gpu/assign",
        json={"service": "open-webui", "gpu_uuid": _VALID_UUID, "confirm": True},
        headers=_AUTH,
    )
    assert resp.status_code == 400
    assert "not GPU-assignable" in resp.json()["detail"]


def test_gpu_assign_rejects_missing_confirm(http_client):
    """confirm omitted (defaults False) → 400."""
    resp = http_client.post(
        "/gpu/assign",
        json={"service": "llamacpp", "gpu_uuid": _VALID_UUID},
        headers=_AUTH,
    )
    assert resp.status_code == 400
    assert "confirm" in resp.json()["detail"].lower()


def test_gpu_assign_rejects_bad_uuid(http_client):
    """Malformed gpu_uuid → 400."""
    resp = http_client.post(
        "/gpu/assign",
        json={"service": "llamacpp", "gpu_uuid": "GPU-notauuid", "confirm": True},
        headers=_AUTH,
    )
    assert resp.status_code == 400
    assert "UUID" in resp.json()["detail"]
