"""The render engine: (declarative source + hardware + catalog) -> RenderedConfig.

This is the drift cure. The ONE context-size value is computed once and flows to every
consumer (.env, Hermes, model-gateway) identically — they cannot disagree, because they're
all derived from the same source. Re-rendering overwrites any hand-edit to a derived output;
only `overrides:` in the source survives.
"""
from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import Any

import yaml

from .catalog import Catalog, DEFAULT_VRAM_RESERVE_GB, Model
from .config import Source
from .hardware import HardwareProfile, detect
from .plugins import PluginRegistry

DEFAULT_PLUGINS_DIR = Path(__file__).resolve().parent.parent / "plugins"

# Deep-merge an override dict onto a derived dict (overrides win, survive regeneration).
def _apply_overrides(derived: dict[str, Any], overrides: dict[str, Any]) -> dict[str, Any]:
    out = dict(derived)
    for k, v in (overrides or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _apply_overrides(out[k], v)
        else:
            out[k] = v
    return out


def _max_ctx_for_vram(model: Model, hw: HardwareProfile, reserve_gb: float) -> int:
    """Largest context that fits after weights + reserve, capped at the model's trained ctx.

    Encodes the KV-math lesson: KV grows ~linearly with ctx, so on a smaller card we cut
    ctx rather than spill. Falls back to ctx_default when we can't estimate (CPU / no kv rate).
    """
    if not hw.has_gpu or not model.kv_kb_per_token:
        return model.ctx_default
    free_after_weights_gb = hw.primary_vram_gb - model.vram_gb - reserve_gb
    if free_after_weights_gb <= 0:
        return min(model.ctx_default, 8192)
    max_tokens = int((free_after_weights_gb * 1024 * 1024) / model.kv_kb_per_token)
    # round down to a tidy multiple of 8K
    max_tokens = (max_tokens // 8192) * 8192
    return max(8192, min(model.ctx_default, max_tokens))


@dataclasses.dataclass
class RenderedConfig:
    hardware: HardwareProfile
    model: Model
    ctx_size: int
    tier: str
    warnings: list[str]
    env: dict[str, str]
    hermes: dict[str, Any]
    model_gateway: dict[str, Any]
    plugins_enabled: list[str]
    compose_profiles: list[str] = dataclasses.field(default_factory=list)
    mcp_servers: list[dict[str, Any]] = dataclasses.field(default_factory=list)

    def manifest(self) -> dict[str, Any]:
        return {
            "hardware": self.hardware.summary(),
            "tier": self.tier,
            "model": {"id": self.model.id, "file": self.model.file, "vram_gb": self.model.vram_gb},
            "ctx_size": self.ctx_size,
            "plugins_enabled": self.plugins_enabled,
            "compose_profiles": self.compose_profiles,
            "mcp_servers": [s["id"] for s in self.mcp_servers],
            "warnings": self.warnings,
            "derived": {
                "env.LLAMACPP_CTX_SIZE": self.env["LLAMACPP_CTX_SIZE"],
                "hermes.context_length": self.hermes["context_length"],
                "model_gateway.ctx": self.model_gateway["ctx"],
            },
        }

    def write(self, out_dir: str | Path) -> None:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        # .env (derived — regenerated every time; hand-edits here do not survive)
        env_lines = ["# GENERATED by ordo render — do not hand-edit; change ordo.yaml instead"]
        env_lines += [f"{k}={v}" for k, v in sorted(self.env.items())]
        (out / ".env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")
        (out / "hermes.context.json").write_text(json.dumps(self.hermes, indent=2), encoding="utf-8")
        (out / "manifest.json").write_text(json.dumps(self.manifest(), indent=2), encoding="utf-8")
        # the mcp-gateway registry, regenerated from kind=mcp plugins (no hand-edit, no drift)
        (out / "mcp-registry.yaml").write_text(
            yaml.safe_dump({"servers": self.mcp_servers}, sort_keys=False), encoding="utf-8")


def _resolve_hardware(source: Source) -> HardwareProfile:
    if source.hardware == "auto" or source.hardware is None:
        return detect()
    return HardwareProfile.from_spec(source.hardware)


def render(source: Source, catalog: Catalog,
           plugins: PluginRegistry | None = None,
           reserve_gb: float = DEFAULT_VRAM_RESERVE_GB) -> RenderedConfig:
    hw = _resolve_hardware(source)
    model, warnings = catalog.resolve(hw, source.model, source.tier, reserve_gb)
    if plugins is None:
        plugins = PluginRegistry.load(DEFAULT_PLUGINS_DIR)

    ctx = _max_ctx_for_vram(model, hw, reserve_gb)

    # --- one source value → every consumer (this is the whole point) ---
    derived: dict[str, Any] = {
        "llamacpp": {
            "ctx_size": ctx,
            "model": model.file,
            "gpu_layers": -1 if hw.has_gpu else 0,
            "kv_cache_type": "q8_0",
            "parallel": 1,
            "flash_attn": "auto",
            "rope_scaling": "none",
            "rope_scale": 1,
            "yarn_orig_ctx": 0,
            "n_predict": 65536,
            "reasoning_budget": 32768,
            "enable_kv_quant": 1,
            "mmproj": model.mmproj or "",
            "extra_args": model.extra_args,
        },
    }
    # `overrides:` survive regeneration; everything else is recomputed each render.
    derived = _apply_overrides(derived, source.overrides)
    lc = derived["llamacpp"]
    ctx = int(lc["ctx_size"])  # re-read in case an override pinned it

    env = {
        "LLAMACPP_MODEL": str(lc["model"]),
        "LLAMACPP_CTX_SIZE": str(ctx),
        "LLAMACPP_GPU_LAYERS": str(lc["gpu_layers"]),
        "LLAMACPP_PARALLEL": str(lc["parallel"]),
        "LLAMACPP_FLASH_ATTN": str(lc["flash_attn"]),
        "LLAMACPP_ROPE_SCALING": str(lc["rope_scaling"]),
        "LLAMACPP_ROPE_SCALE": str(lc["rope_scale"]),
        "LLAMACPP_YARN_ORIG_CTX": str(lc["yarn_orig_ctx"]),
        "LLAMACPP_N_PREDICT": str(lc["n_predict"]),
        "LLAMACPP_REASONING_BUDGET": str(lc["reasoning_budget"]),
        "LLAMACPP_ENABLE_KV_CACHE_QUANTIZATION": str(lc["enable_kv_quant"]),
        "LLAMACPP_KV_CACHE_TYPE_K": str(lc["kv_cache_type"]),
        "LLAMACPP_KV_CACHE_TYPE_V": str(lc["kv_cache_type"]),
        "LLAMACPP_MMPROJ": str(lc["mmproj"]),
        "LLAMACPP_EXTRA_ARGS": str(lc["extra_args"]),
    }
    hermes = {"context_length": ctx, "agent": source.agent}
    model_gateway = {"ctx": ctx, "model_id": "local-chat"}

    # Registry-driven plugin resolution: enable what's requested AND fits AND has its deps.
    enabled, notes = plugins.resolve(source.plugins, hw)
    warnings = warnings + notes
    services = [p for p in enabled if p.kind == "service"]
    mcps = [p for p in enabled if p.kind == "mcp"]
    for p in services:
        env.update(p.env)  # compose services contribute their declared env fragment
    compose_profiles = sorted({p.compose_profile for p in services if p.compose_profile})
    mcp_servers, mcp_notes = _render_mcp(mcps)

    return RenderedConfig(
        hardware=hw, model=model, ctx_size=ctx, tier=(model.tier),
        warnings=warnings + mcp_notes, env=env, hermes=hermes, model_gateway=model_gateway,
        plugins_enabled=[p.id for p in services], compose_profiles=compose_profiles,
        mcp_servers=mcp_servers,
    )


def _render_mcp(mcps: list) -> tuple[list[dict[str, Any]], list[str]]:
    """Build the mcp-gateway registry from kind=mcp plugins. Images MUST be digest-pinned
    (no Docker online-catalog roulette — the leak/drift source in the current stack)."""
    servers: list[dict[str, Any]] = []
    notes: list[str] = []
    for p in mcps:
        image = str(p.mcp.get("image", ""))
        digest = image.split("@sha256:")[-1] if "@sha256:" in image else ""
        if not digest:
            notes.append(f"mcp '{p.id}': image is not digest-pinned — refuse in production")
        elif len(set(digest)) <= 1:  # placeholder like 000.../111...
            notes.append(f"mcp '{p.id}': image digest is a placeholder — set the real sha256")
        servers.append({
            "id": p.id, "name": p.name, "image": image,
            "env": dict(p.mcp.get("env", {}) or {}),
            "tools": list(p.mcp.get("tools", []) or []),
        })
    return servers, notes
