"""The render engine: (declarative source + hardware + catalog) -> RenderedConfig.

This is the drift cure. The ONE context-size value is computed once and flows to every
consumer (.env, Hermes, model-gateway) identically — they cannot disagree, because they're
all derived from the same source. Re-rendering overwrites any hand-edit to a derived output;
only `overrides:` in the source survives.
"""
from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import Any

from .catalog import Catalog, DEFAULT_VRAM_RESERVE_GB, Model
from .config import Source
from .hardware import HardwareProfile, detect

# Deep-merge an override dict onto a derived dict (overrides win, survive regeneration).
def _apply_overrides(derived: dict[str, Any], overrides: dict[str, Any]) -> dict[str, Any]:
    out = dict(derived)
    for k, v in (overrides or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _apply_overrides(out[k], v)
        else:
            out[k] = v
    return out


def _max_ctx_for_vram(model: Model, hw: HardwareProfile, reserve_gb: float) -> int:
    """Largest context that fits after weights + reserve, capped at the model's trained ctx.

    Encodes the KV-math lesson: KV grows ~linearly with ctx, so on a smaller card we cut
    ctx rather than spill. Falls back to ctx_default when we can't estimate (CPU / no kv rate).
    """
    if not hw.has_gpu or not model.kv_kb_per_token:
        return model.ctx_default
    free_after_weights_gb = hw.primary_vram_gb - model.vram_gb - reserve_gb
    if free_after_weights_gb <= 0:
        return min(model.ctx_default, 8192)
    max_tokens = int((free_after_weights_gb * 1024 * 1024) / model.kv_kb_per_token)
    # round down to a tidy multiple of 8K
    max_tokens = (max_tokens // 8192) * 8192
    return max(8192, min(model.ctx_default, max_tokens))


@dataclasses.dataclass
class RenderedConfig:
    hardware: HardwareProfile
    model: Model
    ctx_size: int
    tier: str
    warnings: list[str]
    env: dict[str, str]
    hermes: dict[str, Any]
    model_gateway: dict[str, Any]
    plugins_enabled: list[str]

    def manifest(self) -> dict[str, Any]:
        return {
            "hardware": self.hardware.summary(),
            "tier": self.tier,
            "model": {"id": self.model.id, "file": self.model.file, "vram_gb": self.model.vram_gb},
            "ctx_size": self.ctx_size,
            "plugins_enabled": self.plugins_enabled,
            "warnings": self.warnings,
            "derived": {
                "env.LLAMACPP_CTX_SIZE": self.env["LLAMACPP_CTX_SIZE"],
                "hermes.context_length": self.hermes["context_length"],
                "model_gateway.ctx": self.model_gateway["ctx"],
            },
        }

    def write(self, out_dir: str | Path) -> None:
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        # .env (derived — regenerated every time; hand-edits here do not survive)
        env_lines = ["# GENERATED by ordo render — do not hand-edit; change ordo.yaml instead"]
        env_lines += [f"{k}={v}" for k, v in sorted(self.env.items())]
        (out / ".env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")
        (out / "hermes.context.json").write_text(json.dumps(self.hermes, indent=2), encoding="utf-8")
        (out / "manifest.json").write_text(json.dumps(self.manifest(), indent=2), encoding="utf-8")


def _resolve_hardware(source: Source) -> HardwareProfile:
    if source.hardware == "auto" or source.hardware is None:
        return detect()
    return HardwareProfile.from_spec(source.hardware)


def _plugins_for(source: Source, hw: HardwareProfile) -> list[str]:
    """Media plugins are NVIDIA-only and self-declare that. 'auto' enables what can run."""
    all_media = ["comfyui", "song-gen", "reels", "voice"]
    if source.plugins == "auto":
        return all_media if hw.has_gpu else []
    return [p for p in source.plugins if hw.has_gpu or p not in all_media]


def render(source: Source, catalog: Catalog,
           reserve_gb: float = DEFAULT_VRAM_RESERVE_GB) -> RenderedConfig:
    hw = _resolve_hardware(source)
    model, warnings = catalog.resolve(hw, source.model, source.tier, reserve_gb)

    ctx = _max_ctx_for_vram(model, hw, reserve_gb)

    # --- one source value → every consumer (this is the whole point) ---
    derived: dict[str, Any] = {
        "llamacpp": {
            "ctx_size": ctx,
            "model": model.file,
            "gpu_layers": -1 if hw.has_gpu else 0,
            "kv_cache_type": "q8_0",
        },
    }
    # `overrides:` survive regeneration; everything else is recomputed each render.
    derived = _apply_overrides(derived, source.overrides)
    ctx = int(derived["llamacpp"]["ctx_size"])  # re-read in case an override pinned it

    env = {
        "LLAMACPP_MODEL": str(derived["llamacpp"]["model"]),
        "LLAMACPP_CTX_SIZE": str(ctx),
        "LLAMACPP_GPU_LAYERS": str(derived["llamacpp"]["gpu_layers"]),
        "LLAMACPP_KV_CACHE_TYPE_K": str(derived["llamacpp"]["kv_cache_type"]),
        "LLAMACPP_KV_CACHE_TYPE_V": str(derived["llamacpp"]["kv_cache_type"]),
    }
    hermes = {"context_length": ctx, "agent": source.agent}
    model_gateway = {"ctx": ctx, "model_id": "local-chat"}

    return RenderedConfig(
        hardware=hw, model=model, ctx_size=ctx, tier=(model.tier),
        warnings=warnings, env=env, hermes=hermes, model_gateway=model_gateway,
        plugins_enabled=_plugins_for(source, hw),
    )
