"""Guided setup wizard — produces the declarative source (ordo.yaml).

The one-script's front end. Flow (from the UX decisions): detect hardware → confirm the
auto-picked tier/model (override allowed, warn-but-allow) → cloud keys (opt-in) → agent +
which plugins → write ordo.yaml. Everything downstream renders from that file.

The *logic* (plan + build_source) is separated from *I/O* (prompts) so it's testable without
a TTY — that's also how a headless/CI install works (feed answers, get a source).
"""
from __future__ import annotations

import dataclasses
from pathlib import Path
from typing import Any

import yaml

from .catalog import Catalog
from .hardware import HardwareProfile, detect
from .plugins import PluginRegistry


@dataclasses.dataclass
class WizardPlan:
    """What the wizard would propose, for the user to confirm/override."""
    hardware: HardwareProfile
    tier: str
    model_id: str
    model_name: str
    ctx_estimate: int
    plugins_available: list[str]
    warnings: list[str]


def plan(catalog: Catalog, registry: PluginRegistry,
         hardware: HardwareProfile | None = None) -> WizardPlan:
    hw = hardware or detect()
    model, warns = catalog.best_fit(hw)
    available, notes = registry.resolve("auto", hw)
    return WizardPlan(
        hardware=hw, tier=model.tier, model_id=model.id, model_name=model.name,
        ctx_estimate=model.ctx_default, plugins_available=[p.id for p in available],
        warnings=warns + notes,
    )


def build_source(answers: dict[str, Any] | None = None) -> dict[str, Any]:
    """Turn wizard answers into a valid ordo.yaml dict. All fields optional → sane defaults.

    answers keys (all optional): tier, model, plugins (list|'auto'), agent,
    cloud_fallback (dict), overrides (dict), hardware ('auto'|spec).
    """
    a = answers or {}
    src = {
        "hardware": a.get("hardware", "auto"),
        "tier": a.get("tier", "auto"),
        "model": a.get("model", "auto"),
        "agent": a.get("agent", "hermes"),        # Hermes is the default
        "plugins": a.get("plugins", "auto"),
        "cloud_fallback": a.get("cloud_fallback", {"enabled": False}),
        "overrides": a.get("overrides", {}),
    }
    return src


def write_source(source: dict[str, Any], path: str | Path) -> Path:
    p = Path(path)
    header = ("# Generated by `ordo setup`. This is the single source of truth — edit it and\n"
              "# re-run `ordo render`. Editing rendered outputs does nothing (they regenerate).\n")
    p.write_text(header + yaml.safe_dump(source, sort_keys=False), encoding="utf-8")
    return p


def _prompt(msg: str, default: str) -> str:  # pragma: no cover - interactive only
    ans = input(f"{msg} [{default}]: ").strip()
    return ans or default


def run(catalog: Catalog, registry: PluginRegistry, out_path: str | Path,
        interactive: bool = True, answers: dict[str, Any] | None = None) -> Path:
    """Run the wizard. Non-interactive (answers=...) is the headless/CI path."""
    pl = plan(catalog, registry)
    if not interactive:
        return write_source(build_source(answers), out_path)

    # pragma: no cover below (interactive)
    print(f"Detected: {pl.hardware.summary()}")
    print(f"Proposed: tier={pl.tier}, model={pl.model_name}, "
          f"plugins={', '.join(pl.plugins_available) or '(none)'}")
    for w in pl.warnings:
        print(f"  ! {w}")
    a: dict[str, Any] = {}
    if _prompt("Accept this configuration?", "yes").lower() not in ("y", "yes"):
        a["tier"] = _prompt("Tier (auto/cpu/low/medium/high/ultra)", "auto")
        a["model"] = _prompt("Model id (or 'auto')", "auto")
    a["agent"] = _prompt("Agent", "hermes")
    return write_source(build_source(a), out_path)
