"""The operator's secret store, and what `ordo secrets` materializes from it.

There is one store, and the source's `site:` names it (see `config.secret_backend`):

- `SECRETS_SOURCE` alone (or with `SECRETS_BACKEND: sops`): a SOPS (age) encrypted dotenv file,
  normally in a private repo next to the checkout.
- `SECRETS_BACKEND: infisical`: an Infisical project environment (`INFISICAL_URL`, `INFISICAL_PROJECT`,
  `INFISICAL_ENVIRONMENT`), read through a read-only machine identity. The SOPS file, when
  `SECRETS_SOURCE` is also set, is its offline backup (`ordo secrets backup`) and holds the identities'
  bootstrap credentials (BOOTSTRAP_KEYS; an environment variable of the same name wins).
- neither (a fresh local install with no private repo): `out/secrets.env` itself is the store.

With a SOPS or Infisical store `out/secrets.env` is an artifact, rewritten by `materialize` to hold
exactly the keys the render needs.

Every writer (the wizard's generated secrets, `ordo remote`, the dashboard's local sign-in secret,
`ordo secrets set|rotate|import`) edits the store and then materializes. Values are never printed:
functions here return and raise key NAMES only.

Plaintext never touches disk outside `out/`: a SOPS read is `sops --decrypt` into memory, and a SOPS
write encrypts from an owner-only temp file that is removed before the call returns (sops 3.7 has no
stdin input on Windows).
"""
from __future__ import annotations

import base64
import dataclasses
import os
import re
import secrets as _secrets
import subprocess
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from . import infisical, secret_files
from .config import SECRETS_SOURCE_KEY, secret_backend
from .render import OPTIONAL_SECRET_KEYS

# The site key naming the SOPS file, and the documented place for it: a private repo checked out
# beside this one. A relative value resolves against the checkout, so the same ordo.yaml works on
# any host that keeps the two repos side by side.
DEFAULT_SECRETS_SOURCE = "../ordo-secrets/secrets.env.sops"

# Where sops looks for the age private key when SOPS_AGE_KEY_FILE is unset. sops's own default
# differs per OS (%AppData% on Windows); this one path is what the runbook documents everywhere.
DEFAULT_AGE_KEY_FILE = Path.home() / ".config" / "sops" / "age" / "keys.txt"

# Generated once per install and never rotated: each one hashes or encrypts data that is already
# stored, so a new value makes that data unmatchable or unreadable.
NEVER_ROTATE: dict[str, str] = {
    "LITELLM_SALT_KEY": "it encrypts the credentials LiteLLM stores in Postgres",
    "LANGFUSE_SALT": "it hashes the API keys Langfuse stores",
    "LANGFUSE_ENCRYPTION_KEY": "it encrypts the secrets Langfuse stores",
    "LIVESYNC_E2EE_PASSPHRASE": "it encrypts the notes in CouchDB, and every LiveSync client holds it",
}

# Generated by the wizard, but the value that counts lives in another system afterwards.
ISSUED_ELSEWHERE: dict[str, str] = {
    "LANGFUSE_PUBLIC_KEY": "Langfuse stores the project key pair: rotate it in the Langfuse UI "
                           "(project settings, API keys), then `ordo secrets set` both halves",
    "LANGFUSE_SECRET_KEY": "Langfuse stores the project key pair: rotate it in the Langfuse UI "
                           "(project settings, API keys), then `ordo secrets set` both halves",
    "LANGFUSE_ADMIN_PASSWORD": "it seeds the login only on Langfuse's first boot; change it in the Langfuse UI",
}

# `ordo secrets rotate --internal`: the internal tokens with no outside authority, plus every
# per-consumer LiteLLM key. Other generated keys (COUCHDB_PASSWORD, SEARXNG_SECRET, N8N_API_KEY, the
# local sign-in token) can be rotated by name.
INTERNAL_ROTATION: tuple[str, ...] = (
    "LITELLM_MASTER_KEY", "LITELLM_DB_PASSWORD", "OPS_CONTROLLER_TOKEN", "THROUGHPUT_RECORD_TOKEN",
    "OAUTH2_PROXY_COOKIE_SECRET", "HERMES_API_SERVER_KEY",
    "LANGFUSE_DB_PASSWORD", "LANGFUSE_CLICKHOUSE_PASSWORD", "LANGFUSE_REDIS_AUTH",
    "LANGFUSE_MINIO_SECRET", "LANGFUSE_NEXTAUTH_SECRET",
)
INTERNAL_ROTATION_PREFIXES: tuple[str, ...] = ("LITELLM_KEY_",)

# Stores that keep their own copy of a password: the new value works only after this runs, and
# it must run before the services that read the key are recreated.
ROTATION_STEPS: dict[str, str] = {
    "LITELLM_DB_PASSWORD": "ALTER USER litellm PASSWORD '<new>';  (psql inside litellm-db)",
    "LANGFUSE_DB_PASSWORD": "ALTER USER langfuse PASSWORD '<new>';  (psql inside langfuse-db)",
    "LANGFUSE_CLICKHOUSE_PASSWORD": "ALTER USER clickhouse IDENTIFIED BY '<new>';  (inside langfuse-clickhouse)",
}

# What a rotation does to the people using the stack, once the readers are recreated.
ROTATION_EFFECTS: dict[str, str] = {
    "OAUTH2_PROXY_COOKIE_SECRET": "every oauth2-proxy session ends: sign in again",
    "LANGFUSE_NEXTAUTH_SECRET": "open Langfuse sessions end: sign in again",
}

# ── Generated secrets ──────────────────────────────────────────────────────────
# GENERATED keys are internal shared secrets with no external authority: the store mints a
# strong random value (for `ordo init`, a writer that adds a key, or a rotation) so the operator
# never has to. Everything else in a render's
# `required_secrets` is EXTERNAL (issued by Google / Hugging Face / Tailscale / GitHub): `ordo init`
# leaves it blank for later (a manifest-declared optional one never blocks a bring-up), and
# `ordo remote enable` collects the Google OAuth pair when remote access is turned on.
def _cookie_secret() -> str:
    # oauth2-proxy requires a cookie secret of EXACTLY 16, 24, or 32 bytes (AES-SIV); a urlsafe
    # base64 of 32 random bytes decodes back to 32 bytes and is what oauth2-proxy's docs recommend.
    return base64.urlsafe_b64encode(_secrets.token_bytes(32)).decode("ascii")


def _sk_key(nbytes: int = 24) -> str:
    # LiteLLM requires its master key and every virtual key to start with `sk-`.
    return "sk-" + _secrets.token_hex(nbytes)


SECRET_GENERATORS: dict[str, Any] = {
    "LITELLM_MASTER_KEY": _sk_key,
    # DB credential-encryption salt. Generated ONCE per install and never rotated: changing it makes
    # every credential LiteLLM stored in Postgres unreadable. NEVER_ROTATE below refuses it.
    "LITELLM_SALT_KEY": lambda: _sk_key(32),
    "LITELLM_DB_PASSWORD": lambda: _secrets.token_urlsafe(32),
    "OPS_CONTROLLER_TOKEN": lambda: _secrets.token_urlsafe(32),
    # The local operator's dashboard sign-in while the edge is off (services/dashboard/dashboard.yaml).
    "DASHBOARD_LOCAL_LOGIN_TOKEN": lambda: _secrets.token_urlsafe(32),
    "OAUTH2_PROXY_COOKIE_SECRET": _cookie_secret,
    "SEARXNG_SECRET": lambda: _secrets.token_hex(32),
    "N8N_API_KEY": lambda: _secrets.token_urlsafe(32),
    # Obsidian notes sync (CouchDB LiveSync). token_urlsafe is base64url - JSON-safe for the
    # bridge's generated config, and shell-safe. The E2EE passphrase encrypts note content at rest
    # in CouchDB; the operator enters the SAME value in every Obsidian LiveSync client.
    "COUCHDB_PASSWORD": lambda: _secrets.token_urlsafe(24),
    "LIVESYNC_E2EE_PASSPHRASE": lambda: _secrets.token_urlsafe(32),
    # ── Langfuse (self-hosted tracing) ──
    # Infra credentials for the four backing stores. token_urlsafe is base64url, so these stay
    # safe inside the DATABASE_URL / requirepass / S3-credential shapes that carry them.
    "LANGFUSE_DB_PASSWORD": lambda: _secrets.token_urlsafe(32),
    "LANGFUSE_CLICKHOUSE_PASSWORD": lambda: _secrets.token_urlsafe(32),
    "LANGFUSE_REDIS_AUTH": lambda: _secrets.token_urlsafe(32),
    "LANGFUSE_MINIO_SECRET": lambda: _secrets.token_urlsafe(32),
    "LANGFUSE_NEXTAUTH_SECRET": lambda: _secrets.token_urlsafe(32),
    # SALT hashes the API keys Langfuse stores; ENCRYPTION_KEY encrypts the secrets in its DB, and
    # Langfuse REQUIRES exactly 64 hex characters for it (`openssl rand -hex 32` upstream) - it
    # refuses to boot otherwise. Both are generated ONCE and never rotated, for the same reason as
    # LITELLM_SALT_KEY: rotating makes the stored keys unmatchable and the stored data unreadable.
    "LANGFUSE_SALT": lambda: _secrets.token_hex(32),
    "LANGFUSE_ENCRYPTION_KEY": lambda: _secrets.token_hex(32),
    # Seeded first-login password for the headless-init admin user (LANGFUSE_ADMIN_EMAIL).
    "LANGFUSE_ADMIN_PASSWORD": lambda: _secrets.token_urlsafe(24),
    # The project API keys the headless init CREATES and Hermes then presents. The `pk-lf-` /
    # `sk-lf-` prefixes are not cosmetic: Langfuse issues keys with them, and the Hermes plugin
    # rejects anything else as a leftover placeholder (it would otherwise construct a client that
    # silently drops every trace at flush time).
    "LANGFUSE_PUBLIC_KEY": lambda: "pk-lf-" + _secrets.token_hex(16),
    "LANGFUSE_SECRET_KEY": lambda: "sk-lf-" + _secrets.token_hex(16),
    # ── Evals ──
    # The bearer for Hermes's OpenAI-compatible API server, which the evals runner drives. Hermes
    # refuses to start that listener on a key under 16 characters (its own startup guard), and a
    # holder of this key can run Hermes with its full toolset - so it is minted strong here and
    # stays internal to the project network. Rotatable (`ordo secrets rotate --internal`).
    "HERMES_API_SERVER_KEY": lambda: _secrets.token_urlsafe(32),
    # The dashboard's throughput-record bearer. Optional (the route is open while it is unset), so
    # no render requires it; listed so a store that holds one can rotate it.
    "THROUGHPUT_RECORD_TOKEN": lambda: _secrets.token_hex(32),
}

# Prefix-matched generators: every `LITELLM_KEY_<CONSUMER>` a render requires (one per manifest
# that declares `litellm_key:`) is an internal secret minted here, so adding a consumer needs no
# wizard edit.
SECRET_PREFIX_GENERATORS: dict[str, Any] = {
    "LITELLM_KEY_": _sk_key,
}


def generator_for(key: str) -> Any | None:
    gen = SECRET_GENERATORS.get(key)
    if gen is not None:
        return gen
    for prefix, pgen in SECRET_PREFIX_GENERATORS.items():
        if key.startswith(prefix):
            return pgen
    return None


# The Infisical machine identities' Universal Auth credentials. They live in the SOPS file (or the
# environment) because they are what unlocks Infisical: they cannot be stored in it.
READER_KEYS = ("INFISICAL_ORDO_CLIENT_ID", "INFISICAL_ORDO_CLIENT_SECRET")
WRITER_KEYS = ("INFISICAL_ORDO_WRITER_CLIENT_ID", "INFISICAL_ORDO_WRITER_CLIENT_SECRET")
BOOTSTRAP_KEYS = READER_KEYS + WRITER_KEYS

_RECIPIENT_RE = re.compile(r"^sops_age__list_\d+__map_recipient=(\S+)$", re.MULTILINE)
_OTHER_KEY_GROUP_RE = re.compile(r"^sops_(pgp|kms|gcp_kms|azure_kv|hc_vault)__", re.MULTILINE)


class SecretStoreError(Exception):
    """A store could not be read or written. The message names files and keys, never values."""


class MissingSecrets(SecretStoreError):
    """Required keys have no value in the store."""

    def __init__(self, keys: Sequence[str], store: str):
        self.keys = list(keys)
        super().__init__(f"required secret(s) with no value in {store}: {', '.join(self.keys)}")


class LiveOnlySecrets(SecretStoreError):
    """out/secrets.env holds values the store does not: materializing would lose them."""

    def __init__(self, keys: Sequence[str], store: str,
                 fix: str = "Run `ordo secrets import` first (it adds them to the store), then materialize."):
        self.keys = list(keys)
        super().__init__(
            f"out/secrets.env has value(s) that {store} lacks: {', '.join(self.keys)}. Materializing would "
            f"lose them. {fix}")


# --------------------------------------------------------------------------- #
# dotenv text: the one format every store holds
# --------------------------------------------------------------------------- #


def _entry(line: str) -> tuple[str, str] | None:
    """(key, value) for a `KEY=value` line; None for a comment, a blank line or anything else."""
    if line.lstrip().startswith("#"):
        return None
    key, sep, value = line.partition("=")
    key = key.strip()
    if not sep or not key:
        return None
    return key, value.strip()


def parse_dotenv(text: str) -> dict[str, str]:
    """{KEY: value} in file order. The value is everything after the first `=`, trimmed."""
    values: dict[str, str] = {}
    for line in text.splitlines():
        entry = _entry(line)
        if entry is not None:
            values[entry[0]] = entry[1]
    return values


def update_dotenv(text: str, required_keys: Iterable[str], provided: Mapping[str, str] | None = None,
                  remove: Iterable[str] | None = None) -> tuple[str, list[str], list[str]]:
    """Bring dotenv `text` up to `required_keys`, line by line.

    A provided value replaces the key's value; a required key that is absent or blank gets a
    generated value when it is an internal secret, else an empty entry; a key in `remove` is
    dropped. Every other line (existing values, comments) is kept as is.
    Returns (new text, generated keys, keys left blank)."""
    provided = {k: str(v).strip() for k, v in (provided or {}).items() if str(v or "").strip()}
    drop = set(remove or [])
    existing: dict[str, str] = {}
    kept: list[str] = []
    for line in text.splitlines():
        entry = _entry(line)
        if entry is not None:
            key, value = entry
            if key in drop:
                continue
            existing[key] = value
            if key in provided:
                line = f"{key}={provided[key]}"
        kept.append(line)
    generated: list[str] = []
    blank: list[str] = []
    for key in dict.fromkeys([*required_keys, *provided]):
        if key in provided or existing.get(key):
            if key in provided and key not in existing:
                kept.append(f"{key}={provided[key]}")
            continue
        generator = generator_for(key)
        value = generator() if generator is not None else ""
        (generated if value else blank).append(key)
        if key in existing:   # present but blank: fill that line in place
            kept = [f"{key}={value}" if (_entry(ln) or ("",))[0] == key else ln for ln in kept]
        else:
            kept.append(f"{key}={value}")
    return ("\n".join(kept) + "\n" if kept else ""), generated, blank


def _write_owner_only(path: Path, text: str, mode: int = 0o600) -> None:
    """Write `text` to `path` atomically (temp file in the same directory, then replace), mode 0600
    unless `mode` says otherwise."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


# --------------------------------------------------------------------------- #
# the two stores
# --------------------------------------------------------------------------- #


class PlainStore:
    """out/secrets.env as the store: the local install without a private repo."""

    kind = "local"
    is_sops = False
    # A plain store IS out/secrets.env: materialize leaves it alone.
    materializes = False

    def __init__(self, path: Path):
        self.path = Path(path)

    @property
    def description(self) -> str:
        return str(self.path)

    def exists(self) -> bool:
        return self.path.exists()

    def read_text(self) -> str:
        return self.path.read_text(encoding="utf-8") if self.path.exists() else ""

    def write_text(self, text: str) -> None:
        _write_owner_only(self.path, text)


def age_key_file() -> Path:
    return Path(os.environ.get("SOPS_AGE_KEY_FILE") or DEFAULT_AGE_KEY_FILE)


def age_public_key(key_file: Path) -> str:
    """The `# public key: age1...` line age-keygen writes into a key file."""
    match = re.search(r"^# public key: (age1\S+)", Path(key_file).read_text(encoding="utf-8"), re.MULTILINE)
    if match is None:
        raise SecretStoreError(f"no '# public key:' line in {key_file}")
    return match.group(1)


class SopsStore:
    """A SOPS (age) encrypted dotenv file. Reads decrypt into memory; writes re-encrypt to the same
    recipients the file already has (a new file: SOPS_AGE_RECIPIENTS, else the key file's own
    public key)."""

    kind = "sops"
    is_sops = True
    materializes = True
    live_only_fix = "Run `ordo secrets import` first (it adds them to the store), then materialize."

    def __init__(self, path: Path, sops_bin: str = "sops"):
        self.path = Path(path)
        self.sops_bin = sops_bin

    @property
    def description(self) -> str:
        return f"{self.path} (SOPS)"

    @property
    def label(self) -> str:
        return self.path.name

    def exists(self) -> bool:
        return self.path.exists()

    def _sops(self, args: list[str]) -> bytes:
        env = dict(os.environ)
        env["SOPS_AGE_KEY_FILE"] = str(age_key_file())
        # dotenv must be named explicitly: sops 3.7 on Windows does not detect it from the content.
        argv = [self.sops_bin, *args[:1], "--input-type", "dotenv", "--output-type", "dotenv", *args[1:]]
        try:
            proc = subprocess.run(argv, capture_output=True, env=env, timeout=120)
        except FileNotFoundError as e:
            raise SecretStoreError(f"`{self.sops_bin}` is not installed (needed for {self.path})") from e
        if proc.returncode != 0:
            # A decrypt error names the key problem (no data key, bad MAC) and cannot hold plaintext. An
            # encrypt error can quote the offending input line, which is plaintext: report only the code.
            lines = proc.stderr.decode("utf-8", "replace").strip().splitlines()
            detail = lines[-1] if args[0] == "--decrypt" and lines else f"exit code {proc.returncode}"
            raise SecretStoreError(f"sops {args[0]} failed for {self.path}: {detail}")
        return proc.stdout

    def read_text(self) -> str:
        if not self.path.exists():
            raise SecretStoreError(f"no SOPS file at {self.path}: create it with `ordo secrets import`")
        return self._sops(["--decrypt", str(self.path)]).decode("utf-8").replace("\r\n", "\n")

    def recipients(self) -> list[str]:
        """The age recipients the existing file is encrypted to (read from its cleartext metadata)."""
        metadata = self.path.read_text(encoding="utf-8")
        found = _RECIPIENT_RE.findall(metadata)
        if _OTHER_KEY_GROUP_RE.search(metadata) or not found:
            raise SecretStoreError(f"{self.path} is not encrypted to age recipients only; "
                                   "re-encrypt it with age (sops updatekeys) first")
        return found

    def _new_file_recipients(self) -> list[str]:
        env_recipients = os.environ.get("SOPS_AGE_RECIPIENTS", "").strip()
        if env_recipients:
            return [r.strip() for r in env_recipients.split(",") if r.strip()]
        key_file = age_key_file()
        if not key_file.exists():
            raise SecretStoreError(f"no age key at {key_file}: create one with `age-keygen -o {key_file}` "
                                   "or set SOPS_AGE_KEY_FILE / SOPS_AGE_RECIPIENTS")
        return [age_public_key(key_file)]

    def write_text(self, text: str, recipients: Sequence[str] | None = None) -> None:
        if recipients is None:
            recipients = self.recipients() if self.path.exists() else self._new_file_recipients()
        fd, plaintext_path = tempfile.mkstemp(prefix="ordo-secrets-", suffix=".env")
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            os.chmod(plaintext_path, 0o600)
            ciphertext = self._sops(["--encrypt", "--age", ",".join(recipients), plaintext_path])
        finally:
            Path(plaintext_path).unlink(missing_ok=True)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(prefix=f".{self.path.name}.", dir=self.path.parent)
        try:
            with os.fdopen(fd, "wb") as f:
                f.write(ciphertext.replace(b"\r\n", b"\n"))
            os.replace(tmp, self.path)
        except BaseException:
            Path(tmp).unlink(missing_ok=True)
            raise


class InfisicalStore:
    """An Infisical project environment as the store, through the client in ordo/infisical.py.

    Reads use the read-only identity (READER_KEYS). A write (`write_text`, the one path every writer
    takes) is applied as per-key create/update/delete calls with the optional writer identity
    (WRITER_KEYS); without one it is refused, naming the keys to change in the Infisical UI. It never
    falls back to the SOPS file. Each credential is read from the environment first, then from the
    `backup` store (the SOPS file `SECRETS_SOURCE` names), decrypted at most once."""

    kind = "infisical"
    is_sops = False
    materializes = True

    def __init__(self, url: str, project: str, environment: str, *, backup: PlainStore | SopsStore | None = None,
                 environ: Mapping[str, str] | None = None, transport: infisical.Transport | None = None):
        self.url = url.rstrip("/")
        self.project = project
        self.environment = environment
        self.backup = backup
        self._environ = environ if environ is not None else os.environ
        self._transport = transport
        self._backup_values: dict[str, str] | None = None
        self._clients: dict[str, infisical.InfisicalClient] = {}

    @property
    def description(self) -> str:
        return f"Infisical project '{self.project}' environment '{self.environment}' at {self.url}"

    @property
    def label(self) -> str:
        return f"Infisical project '{self.project}' environment '{self.environment}'"

    @property
    def live_only_fix(self) -> str:
        return (f"Add them to {self.label} first (the Infisical UI, or `ordo secrets set KEY --from-stdin` "
                "with a writer identity), then materialize.")

    def exists(self) -> bool:
        return True

    def _credential(self, name: str) -> str:
        """The environment variable `name`, else the backup store's value for it."""
        value = str(self._environ.get(name, "") or "").strip()
        if value or self.backup is None:
            return value
        if self._backup_values is None:
            self._backup_values = parse_dotenv(self.backup.read_text()) if self.backup.exists() else {}
        return self._backup_values.get(name, "")

    def _client(self, role: str) -> infisical.InfisicalClient | None:
        """The `reader` or `writer` client; None when that identity has no credentials."""
        if role not in self._clients:
            id_key, secret_key = READER_KEYS if role == "reader" else WRITER_KEYS
            client_id, client_secret = self._credential(id_key), self._credential(secret_key)
            if not (client_id and client_secret):
                return None
            self._clients[role] = infisical.InfisicalClient(
                self.url, client_id, client_secret, identity=role, id_names=f"{id_key} / {secret_key}",
                transport=self._transport)
        return self._clients[role]

    def _where_credentials_live(self) -> str:
        where = f"the SOPS file {self.backup.path}" if isinstance(self.backup, SopsStore) else "the SOPS file"
        return f"{where} (site {SECRETS_SOURCE_KEY}) or the environment"

    def values(self) -> dict[str, str]:
        """{KEY: value} of the environment, read with the reader identity."""
        client = self._client("reader")
        if client is None:
            raise SecretStoreError(f"no Infisical reader identity: set {READER_KEYS[0]} and {READER_KEYS[1]} in "
                                   f"{self._where_credentials_live()}")
        try:
            values = client.read_secrets(self.project, self.environment)
        except infisical.InfisicalError as e:
            raise SecretStoreError(str(e)) from None
        multi_line = [k for k, v in values.items() if "\n" in v or "\r" in v]
        if multi_line:
            raise SecretStoreError(f"{self.label}: multi-line value(s) cannot be materialized into a dotenv "
                                   f"file: {', '.join(multi_line)}")
        return values

    def read_text(self) -> str:
        return "".join(f"{key}={value}\n" for key, value in self.values().items())

    def write_text(self, text: str) -> None:
        """Make the environment hold exactly the entries of dotenv `text` (the diff against a fresh read)."""
        wanted = parse_dotenv(text)
        current = self.values()
        creates = [k for k in wanted if k not in current]
        updates = [k for k in wanted if k in current and wanted[k] != current[k]]
        deletes = [k for k in current if k not in wanted]
        changed = creates + updates + deletes
        if not changed:
            return
        writer = self._client("writer")
        if writer is None:
            raise SecretStoreError(
                f"{self.label} is the secret source and no writer identity is configured ({WRITER_KEYS[0]} / "
                f"{WRITER_KEYS[1]} in {self._where_credentials_live()}): nothing was written. Change "
                f"{', '.join(changed)} in the Infisical UI, then run `ordo secrets materialize`")
        done: list[str] = []
        try:
            for key in creates:
                writer.write_secret(self.project, self.environment, "POST", key, wanted[key])
                done.append(key)
            for key in updates:
                writer.write_secret(self.project, self.environment, "PATCH", key, wanted[key])
                done.append(key)
            for key in deletes:
                writer.write_secret(self.project, self.environment, "DELETE", key)
                done.append(key)
        except infisical.InfisicalError as e:
            written = f" (already written: {', '.join(done)})" if done else " (nothing was written)"
            raise SecretStoreError(f"{e}{written}") from None


Store = PlainStore | SopsStore | InfisicalStore


def resolve_source_path(value: str, repo_root: Path) -> Path:
    path = Path(value).expanduser()
    return (path if path.is_absolute() else Path(repo_root) / path).resolve()


def store_for(site: Mapping[str, Any], out_dir: Path, repo_root: Path, *,
              environ: Mapping[str, str] | None = None, transport: infisical.Transport | None = None) -> Store:
    """The store a source's `site:` names: an Infisical project (SECRETS_BACKEND: infisical), its SOPS
    file (SECRETS_SOURCE), or out/secrets.env when neither is set."""
    try:
        backend = secret_backend(dict(site or {}))
    except ValueError as e:
        raise SecretStoreError(str(e)) from None
    sops = SopsStore(resolve_source_path(backend.sops_path, repo_root)) if backend.sops_path else None
    if backend.kind == "infisical":
        return InfisicalStore(backend.url, backend.project, backend.environment, backup=sops,
                              environ=environ, transport=transport)
    if sops is not None:
        return sops
    return PlainStore(Path(out_dir) / "secrets.env")


def sops_file_of(store: Store) -> SopsStore | None:
    """The SOPS file behind a store: the store itself, an Infisical store's backup, or None."""
    if isinstance(store, SopsStore):
        return store
    if isinstance(store, InfisicalStore) and isinstance(store.backup, SopsStore):
        return store.backup
    return None


# --------------------------------------------------------------------------- #
# what a render needs, and materializing it
# --------------------------------------------------------------------------- #


@dataclasses.dataclass(frozen=True)
class SecretFile:
    """A file-delivered secret one service mounts: the store key whose value is written to
    out/secrets/<file> (ordo/secret_files.py). Services that read the same key share the file."""
    key: str
    file: str
    service: str


@dataclasses.dataclass(frozen=True)
class SecretNeeds:
    """The secret NAMES a render needs: env-form (`required`, of which `optional` may stay blank)
    and file-form (`files`)."""
    required: tuple[str, ...]
    optional: tuple[str, ...] = ()
    files: tuple[SecretFile, ...] = ()

    @classmethod
    def from_manifest(cls, manifest: Mapping[str, Any]) -> SecretNeeds:
        return cls(required=tuple(manifest.get("required_secrets") or ()),
                   optional=tuple(manifest.get("optional_secrets") or ()),
                   files=tuple(SecretFile(**entry) for entry in manifest.get("secret_files") or ()))

    @classmethod
    def from_render(cls, rendered: Any) -> SecretNeeds:
        return cls.from_manifest(rendered.manifest())


@dataclasses.dataclass
class Materialized:
    secrets_env: Path
    blank_required: list[str]
    blank_optional: list[str]
    files: list[Path]
    # Files under out/secrets/ that no render declares any more. Kept: a running container may still
    # mount one, and a restart of that container needs its bind source to exist. Remove one after
    # recreating the services that used it.
    stale_files: list[Path] = dataclasses.field(default_factory=list)


# The file-secret directory is owner-only on the host; each file in it is world-readable, because a
# bind-mounted file keeps its host mode and a container reads it as its own uid (oauth2-proxy runs as
# 65532, gpu-gate as 10001). The directory, not the file, is what keeps other host users out.
SECRET_FILES_DIR_MODE = 0o700
SECRET_FILE_MODE = 0o644


def _write_file_secrets(out: Path, files: Sequence[SecretFile], values: Mapping[str, str]) -> tuple[list[Path], list[Path]]:
    """Write each declared file secret once, and the digests every compose call loads. Returns
    (written files, stale files)."""
    by_file = {secret.file: secret.key for secret in files}
    directory = out / "secrets"
    directory.mkdir(parents=True, exist_ok=True)
    os.chmod(directory, SECRET_FILES_DIR_MODE)
    written = []
    for file, key in by_file.items():
        path = directory / file
        _write_owner_only(path, values.get(key, ""), mode=SECRET_FILE_MODE)
        written.append(path)
    stale = sorted(p for p in directory.iterdir()
                   if p.is_file() and not p.name.startswith(".") and p.name not in by_file)
    digests = [
        "# GENERATED by `ordo secrets materialize`: a digest of each file secret's value (never the value).",
        "# Each mount's label interpolates its digest, so a rotated value recreates its readers.",
    ]
    digests += [f"{secret_files.digest_var(key)}={secret_files.digest(values.get(key, ''))}"
                for key in sorted(set(by_file.values()))]
    _write_owner_only(out / secret_files.DIGESTS_ENV_FILE, "\n".join(digests) + "\n")
    return written, stale


def materialize(store: Store, needs: SecretNeeds, out_dir: Path, *, strict: bool = True,
                removed: Iterable[str] = ()) -> Materialized:
    """Write what the render needs from the store: out/secrets.env (from a SOPS store; a plain store
    already is that file), each file-delivered secret under out/secrets/, and their digests in
    out/secret-files.env.

    `strict` raises MissingSecrets (nothing written) when a required, non-optional key has no value;
    a writer that only reports blanks passes strict=False. A SOPS materialize refuses (LiveOnlySecrets,
    nothing written) to overwrite a value in out/secrets.env the store lacks, except the keys a writer
    just `removed` from the store on purpose."""
    out = Path(out_dir)
    values = parse_dotenv(store.read_text())
    blank_required = [k for k in needs.required if k not in needs.optional and not values.get(k)]
    blank_optional = [k for k in needs.required if k in needs.optional and not values.get(k)]
    if strict and blank_required:
        raise MissingSecrets(blank_required, store.description)
    secrets_env = out / "secrets.env"
    if store.materializes:
        live = parse_dotenv(secrets_env.read_text(encoding="utf-8")) if secrets_env.exists() else {}
        skip = set(removed)
        lost = [k for k, v in live.items() if v and not values.get(k) and k not in skip]
        if lost:
            raise LiveOnlySecrets(lost, store.description, store.live_only_fix)
    files, stale = _write_file_secrets(out, needs.files, values)
    if store.materializes:
        lines = [
            f"# GENERATED by `ordo secrets materialize` from {store.label}. Do not edit: the next",
            "# materialize replaces this file. Change a value with `ordo secrets set KEY`.",
        ]
        lines += [f"{k}={values.get(k, '')}" for k in needs.required]
        lines += [f"{k}={values[k]}" for k in OPTIONAL_SECRET_KEYS if values.get(k) and k not in needs.required]
        _write_owner_only(secrets_env, "\n".join(lines) + "\n")
    return Materialized(secrets_env, blank_required, blank_optional, files, stale)


# --------------------------------------------------------------------------- #
# edits: update, set, rotate, import
# --------------------------------------------------------------------------- #


def update(store: Store, required_keys: Iterable[str], provided: Mapping[str, str] | None = None,
           remove: Iterable[str] | None = None) -> tuple[list[str], list[str]]:
    """`update_dotenv` applied to the store; written only when something changed (a SOPS file is
    not re-encrypted, and so not churned in git, by a no-op). Returns (generated, blank) keys."""
    text = store.read_text()
    new_text, generated, blank = update_dotenv(text, required_keys, provided, remove)
    if new_text != text:
        store.write_text(new_text)
    return generated, blank


def rotation_refusal(key: str) -> str | None:
    """Why `key` must not be rotated from the store, or None when it may be."""
    if key in NEVER_ROTATE:
        return f"{key}: never rotate: {NEVER_ROTATE[key]}"
    if key in ISSUED_ELSEWHERE:
        return f"{key}: {ISSUED_ELSEWHERE[key]}"
    if generator_for(key) is None:
        return f"{key} is issued by an outside service: regenerate it there, then `ordo secrets set {key} --from-stdin`"
    return None


def is_internal(key: str) -> bool:
    return key in INTERNAL_ROTATION or key.startswith(INTERNAL_ROTATION_PREFIXES)


def rotate(store: Store, keys: Sequence[str]) -> list[str]:
    """Give each key a fresh generated value. Refuses (SecretStoreError, nothing written) a key the
    policy protects or one the store does not hold (a new key is `set --generate`)."""
    present = parse_dotenv(store.read_text())
    problems = [r for k in keys if (r := rotation_refusal(k))]
    problems += [f"{k} is not in {store.description} (add it with `ordo secrets set {k} --generate`)"
                 for k in keys if not rotation_refusal(k) and not present.get(k)]
    if problems:
        raise SecretStoreError("; ".join(problems))
    fresh = {key: generator_for(key)() for key in keys}   # rotation_refusal checked each has one
    update(store, [], provided=fresh)
    return list(keys)


def internal_keys(store: Store) -> list[str]:
    """The keys `rotate --internal` rotates: every internal token the store holds a value for."""
    return [k for k, v in parse_dotenv(store.read_text()).items() if v and is_internal(k)]


@dataclasses.dataclass
class Imported:
    added: list[str]
    differing: list[str]
    files_added: list[str]


def import_values(store: Store, live_path: Path, *, files: Sequence[SecretFile] = (),
                  files_dir: Path | None = None, overwrite: bool = False) -> Imported:
    """Add to the store every non-empty value in `live_path` (out/secrets.env) it lacks, and each
    file-form secret found in `files_dir` (the retired OPERATOR_SECRETS_DIR). A key the store holds
    with a different value is named in `differing` and kept, unless `overwrite`. Creates the store
    when it does not exist."""
    text = store.read_text() if store.exists() else ""
    stored = parse_dotenv(text)
    live = parse_dotenv(Path(live_path).read_text(encoding="utf-8")) if Path(live_path).exists() else {}
    provided: dict[str, str] = {}
    added: list[str] = []
    differing: list[str] = []
    for key, value in live.items():
        if not value:
            continue
        if not stored.get(key):
            provided[key] = value
            added.append(key)
        elif stored[key] != value:
            differing.append(key)
            if overwrite:
                provided[key] = value
    files_added: list[str] = []
    for secret in files:
        path = Path(files_dir) / secret.file if files_dir else None
        if path is None or not path.is_file() or stored.get(secret.key) or secret.key in provided:
            continue
        value = path.read_text(encoding="utf-8").strip()
        if value:
            provided[secret.key] = value
            files_added.append(secret.key)
    if not provided and not store.exists():
        raise SecretStoreError(f"nothing to import: {live_path} holds no value, so {store.description} "
                               "was not created")
    if provided:
        new_text, _, _ = update_dotenv(text, [], provided=provided)
        store.write_text(new_text)
    return Imported(added, differing, files_added)


# --------------------------------------------------------------------------- #
# the offline copy of an Infisical store
# --------------------------------------------------------------------------- #


@dataclasses.dataclass
class BackedUp:
    added: list[str]
    updated: list[str]
    only_in_backup: list[str]


def backup(source: InfisicalStore, target: SopsStore) -> BackedUp:
    """Copy every value of the Infisical environment into the SOPS file: keys it lacks are added, keys
    with a different value updated. Keys only the SOPS file holds (the bootstrap credentials, anything
    removed from Infisical) are kept and named; the file is re-encrypted only when something changed."""
    values = {k: v for k, v in source.values().items() if v and k not in BOOTSTRAP_KEYS}
    text = target.read_text() if target.exists() else ""
    stored = parse_dotenv(text)
    added = [k for k in values if not stored.get(k)]
    updated = [k for k in values if stored.get(k) and stored[k] != values[k]]
    only_in_backup = [k for k, v in stored.items() if v and k not in values and k not in BOOTSTRAP_KEYS]
    if added or updated:
        new_text, _, _ = update_dotenv(text, [], provided={k: values[k] for k in added + updated})
        target.write_text(new_text)
    return BackedUp(added, updated, only_in_backup)


def backup_status(value: str, backup_value: str) -> str:
    """How the SOPS backup holds a key the active store has a value for."""
    if backup_value == value:
        return "backed up"
    return "stale in backup" if backup_value else "not in backup"
